### ISSUE TITLE
Implementing localization

### ISSUE THREAD

**Issue by yashha** [adamjgrant/vegankit-v1#1]
@adamjgrant 
I like your site and would help you get translations going.
I could try to implement an localization option and offer german translations. (although I don't know anything about rails yet, but it is probably not that difficult ;)) 
Interested?

Greets 
Yasar

**Comment by adamjgrant** [comment]
Hi @yashha 

I actually run vegankit on static files now, built by gulp and manage translations in JSON files. Would love to have your help. Mind sending me an email at hello@adamgrant.me?
